language: generic
sudo: required

branches:
  only:
   - staging
   - trying
   - master

services:
  - docker

env:
  - TARGET=ansibleCheck
  - TARGET=shellCheck
  - TARGET=shfmtCheck

install:
 - docker build -t appliance-build:latest docker

script:
 - ./scripts/docker-run.sh gradle $TARGET
