on: [push, pull_request]

jobs:
  check-ansible:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew ansibleCheck
  check-shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew shellCheck
  check-shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew shfmtCheck
